# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BLEScanList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'BabyBluetooth','~> 0.7.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SVProgressHUD'
  use_frameworks!
  
  

  # Pods for BLEScanList

end
